#!/bin/bash
 
#PBS -l walltime=5:00:00,select=1:ncpus=4:ngpus=1:mem=8gb
#PBS -q sockeye
#PBS -N dlc_analyse
#PBS -A st-sturvey-1-gpu
#PBS -m abe
#PBS -j oe
 
################################################################################

cd $PBS_O_WORKDIR
source /project/st-sturvey-1/PrecisionHealthVirtualEnvironment/Software/miniconda3/etc/profile.d/conda.sh
conda activate DLC-GPU-Environment

python dlc_train.py &> out_dlc_train.txt
