---
title: "BCCHR Precision Health Bootcamp - Terms and Definitions"
author: Nikita Telkar
output: 
  rmdformats::downcute:
    self_contained: true
    default_style: "light"
    downcute_theme: "default"
    style_switcher: false
    toc_depth: 4
    keep_md: yes

---

***  

> This document contains the most common commands/functions and computaional terms used within Linux, as well as within the BCCHR Precision Health Bootcamp  

***  

### Virtual Environment/Machine 

A virtual operating system workspace. Each guest can create multiple VMs within their account, with each having it's own software and dependencies.  

- Virtual Machine = A cookie, cake, or pasta - the base ingredient Flour (your server operating system) can be divided up to make several different recipes.  

***  

### Container 

A common operating system bundle consisting of multiple applications/software, plus all their dependencies, which can be loaded by each user (and hence they wouldn't have to install their own software.  

- Container = A meal plan box containing the same recipe, instructions, and ingredients for each person. You can always add your own ingredients (personal software on a container) too.  

*** 